### ISSUE TITLE
KineticHUD crashes to desktop on converting Joker

### ISSUE THREAD

**Issue by wanderso** [offyerrocker/KineticHUD#1]
Sorry to bother you, but I just started installing Payday mods, and with KineticHUD active, Payday 2 immediately crashes the moment I convert a Joker. When I deactivate KineticHUD, the crashes stop. I really want to use this HUD - is there any workaround, or way you could fix this?

**Comment by offyerrocker** [comment]
Thanks for the report! It's no bother, you can always contact me about issues with my mods. Sorry I haven't updated KineticHUD in a while.

I've been sitting on some crash fixes for a while, including one for the Joker conversion crash you're experiencing. You can try downloading this new version (it should be labeled as the v.142 beta), which should fix that bug (and a couple other crashes).

As an alternative, you can take the public version available from modworkshop and replacing the file `KineticHUD/lua/groupaibasestate.lua` with the one found in the latest GitHub version.

Hope that works for you! If it doesn't, or you run into more issues, feel free to post another issue here or contact me directly.
